### ISSUE TITLE
[BUG REPORT]: New Users not seen in Admin Screen

### ISSUE THREAD

**Issue by ScottMassa** [USACE/instrumentation#196] opened 2024-09-04 19:34 UTC
## Describe the bug
New users who have created an account in Login.gov are not seen on "Add New Member" search.
Members are confirmed to have an account using login.gov and USACE email address

## Steps To Reproduce
1. Go to Admin Screen
2. Click on Add New Member
3. type Kerby or Carrasquillo
4. no matches are found

## Expected behavior
New users accounts are found

## Actual behavior
No account found

## Screenshots
<img width="203" alt="image" src="https://github.com/user-attachments/assets/40b94c78-04a6-4802-8e4e-887de54dffa6">

Windows 10
Edge 128

**Comment by dennisgsmith** [comment] 2024-09-07 00:44
This should now be _mostly_ fixed with https://github.com/USACE/instrumentation-api/releases/tag/v3.4.2. There was a false positive caused by an unexpected type coercion.

Note: users will need to log in to MIDAS with CAC once more for their profiles to show up.

Will close once enhanced user error messaging is added (in the case where true positive).

**Closed as completed** 2024-09-12 15:02 UTC
Labels: bug
