### ISSUE TITLE
[BUG REPORT]: Upload Timeseries data via Uploader

### ISSUE THREAD

**Issue by ScottMassa** [USACE/instrumentation#181] opened 2024-08-22 15:14 UTC
## Describe the bug
Uploader tool returns "API Error: undefined" when uploading a timeseries measurement

## Steps To Reproduce
1. Go to Uploader tab and import timeseries measurement
2. Click Upload.

## Expected behavior
Data is uploaded.

## Actual behavior
API error: Undefined, and 400 Bad Request

## Screenshots
<img width="954" alt="image" src="https://github.com/user-attachments/assets/f38b6feb-c66f-4083-936e-ba7d16b28d2b">

## Desktop (please complete the following information):
 - OS: Windows 10
 - Browser: Microsoft Edge
 - Version 127?

**Comment by ScottMassa** [comment] 2024-08-22 16:49
Data is not update, also TS UUID is not populated in the Parsed Screen, See attached.
<img width="533" alt="image" src="https://github.com/user-attachments/assets/2e4c5f93-88fe-42b3-a56e-dd44dabc3d98">

**Comment by dennisgsmith** [comment] 2024-08-22 17:01
@ScottMassa thanks for the bug report. I'm currently looking into this -- it seems there is an issue with the uploader not populating the timeseries_id field in the request payload:
<img width="1573" alt="Screenshot 2024-08-22 at 12 59 35 PM" src="https://github.com/user-attachments/assets/86f0d7fd-6ca4-4cac-9e97-ebd2316bd8c8">

I'll let you know once this issue is resolved.

**Comment by dennisgsmith** [comment] 2024-08-22 18:59
@ScottMassa Looking at the code, it seems that the parser expects a "timeseries_id" column in the uploaded csv. Is this the intended behavior? Or it the expectation to be able to select a single timeseries from the dropdown list within the uploader?

@KevinJJackson is currently out of office -- I'll attempt to resolve on my own but will make sure he's aware of this issue once he returns tomorrow.

**Comment by ScottMassa** [comment] 2024-08-22 20:40
We have always selected the timeseries ID from the drop down list, or it’s been prepopulated if we select upload from the timeseries on the instrument tab.  The next scope of work will have an equivalency table so we can upload multiple timeseries at once.
I think this feature broke since last Wednesday night, we just noticed it today.

Scott

**Comment by KevinJJackson** [comment] 2024-08-23 15:25
Fixed in latest release https://github.com/USACE/instrumentation-ui/releases/tag/v0.17.2

**Closed as completed by KevinJJackson** 2024-08-23 15:25 UTC
Labels: bug
